### ISSUE TITLE
Tekster og links til bunden af Symbolkommunikation

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol#129]
DK: (banner: http://www.positiverne.dk/symbol/try-free-symbol/banner-da.json)
Om Symbolkommunikation (link til http://positiverne.dk/symbol/)

Facebook (link til https://www.facebook.com/symbolkommunikation) 
Google+ (link til https://plus.google.com/116499944048175729358/posts)

©  Symbolkommunikation - struktur til mennesker med ADHD, Autisme, Aspergers syndrom og andre kognitive udfordringer.

EN: (banner: http://www.positiverne.dk/symbol/try-free-symbol/banner-en.json)
About Symbolkommunikation (link til http://positiverne.dk/symboluk/)

Facebook (link til https://www.facebook.com/symbolkommunikation) 
Google+ (link til https://plus.google.com/116499944048175729358/posts)

©  Symbolkommunikation - Provides structure for people with ADHD, Autism, Asperger syndrome and other cognitive challenges.

DE: (banner: http://www.positiverne.dk/symbol/try-free-symbol/banner-de.json)
Über Symbolkommunikation (link til http://positiverne.dk/symboluk/)

Facebook (link til https://www.facebook.com/symbolkommunikation) 
Google+ (link til https://plus.google.com/116499944048175729358/posts)

©  Symbolkommunikation - Struktur für Menschen mit ADHS, Autismus, Asperger-Syndrom und anderen kognitiven behinderungen.

SE: (banner: http://www.positiverne.dk/symbol/try-free-symbol/banner-se.json)
Om Symbolkommunikation (link til http://positiverne.dk/symbol/)

Facebook (link til https://www.facebook.com/symbolkommunikation) 
Google+ (link til https://plus.google.com/116499944048175729358/posts)

©  Symbolkommunikation - struktur för personer med ADHD, autism, Aspergers syndrom och andra kognitiva utmaningar.

NO: (banner: http://www.positiverne.dk/symbol/try-free-symbol/banner-no.json)
Om Symbolkommunikation (link til http://positiverne.dk/symbol/)

Facebook (link til https://www.facebook.com/symbolkommunikation) 
Google+ (link til https://plus.google.com/116499944048175729358/posts)

©  Symbolkommunikation - struktur for personer med ADHD, autisme, Asperger syndrom og andre kognitive utfordringer.

**Comment by michaelkrog** [comment]
Der er noget galt med encodningen af teksten.

Prøv f.eks at åben den i chrome:
http://www.positiverne.dk/symbol/try-free-symbol/banner-en.json

Hos mig ser det sådan her ud:
```
{
Â  Â  â€œimageâ€: â€œ<http://www.positiverne.dk/symbol/try-free-symbol/EN.pngâ€,
Â  Â  â€œlinkâ€: â€œ<http://www.positiverne.dk/symbol/try-free-3-months/>â€
}
```

**Comment by michaelkrog** [comment]
Flyttet til https://github.com/henrikravn/symbol-mobile/issues/64
